import Head from "next/head";
import Layout from "components/Layout/Layout";
import PageTitle from "components/Home/PageTitle/PageTitle";
import CategoryBar from "components/Home/CategoryBar/CategoryBar";
import FeaturedWrapper from "components/Home/Featured/FeaturedWrapper";
import ProductLinkWrapper from "components/Home/ProductLink/ProductLinkWrapper";
import BrandsWrapper from "components/Home/BrandsWrapper/BrandsWrapper";
import ProductsRow from "components/Global/ProductsRow/ProductsRow";
import { useSelector } from "react-redux";
import Slider from "components/Global/Slider/Slider";
import routes from "utils/constants/routes";

export default function Home() {
  //states
  const { newProducts, bestSellers, categoriesProducts } = useSelector(
    (state) => state.home
  );
  const { loggedIn, userWishlist } = useSelector((state) => state.user);

  return (
    <>
      <Head>
        <title>Duran Shop</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <PageTitle className="mt-4 h-96" />
        <CategoryBar />
        <FeaturedWrapper />
        <ProductLinkWrapper />
        <BrandsWrapper />
        <ProductsRow
          name="جدیدترین"
          list={newProducts || []}
          allLink={routes.result.path + "?orderby=15"}
        />
        <ProductsRow
          name="پرفروش ها"
          list={bestSellers || []}
          allLink={routes.result.path + "?orderby=20"}
        />
        <Slider />
        {categoriesProducts &&
          categoriesProducts.map((item) => {
            return (
              <ProductsRow
                key={item.categoryId}
                name={item.categoryName}
                list={item.products || []}
                allLink={routes.result.path + "?cid=" + item.categoryId}
              />
            );
          })}
      </Layout>
    </>
  );
}
